### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by RashmiChandran** [krish-dev/cordova-plugin-k-imagecropper#10]
Hi,

I am using this plugin with ionic 3 application:
The app crashes with the following issues:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com. PID: 10669
                                                                      java.lang.NoSuchMethodError: No static method getScreenWidthDp(Landroid/content/res/Resources;)I in class Landroid/support/v4/content/res/ConfigurationHelper; or its super classes (declaration of 'android.support.v4.content.res.ConfigurationHelper' appears in /data/app//split_lib_dependencies_apk.apk)
                                                                          at android.support.v7.view.ActionBarPolicy.getMaxActionButtons(ActionBarPolicy.java:57)
                                                                          at android.support.v7.widget.ActionMenuPresenter.initForMenu(ActionMenuPresenter.java:108)
                                                                          at android.support.v7.view.menu.MenuBuilder.addMenuPresenter(MenuBuilder.java:264)
                                                                          at android.support.v7.widget.Toolbar.setMenu(Toolbar.java:569)
                                                                          at android.support.v7.widget.ToolbarWidgetWrapper.setMenu(ToolbarWidgetWrapper.java:369)
                                                                          at android.support.v7.widget.ActionBarOverlayLayout.setMenu(ActionBarOverlayLayout.java:714)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.preparePanel(AppCompatDelegateImplV9.java:1362)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.doInvalidatePanelMenu(AppCompatDelegateImplV9.java:1648)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9$1.run(AppCompatDelegateImplV9.java:140)
                                                                          at android.os.Handler.handleCallback(Handler.java:754)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:163)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Ionic info:**

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.4.0 ios 4.5.0 windows 4.4.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.10.1
    npm  : 4.2.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

Thanks in advance!

**Comment by krish-dev** [comment]
resolved in version 1.2.0
